version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    build: .
    command: /bin/bash -l -c "sudo rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes: 
      - .:/home/hosting/blog
    depends_on:
      - db
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    command: /bin/bash -l -c "export NODE_OPTIONS=--openssl-legacy-provider && npm run serve"
    volumes:
      - ./frontend:/home/hosting/blog-front
    ports:
      - "8080:8080"
    tty: true
volumes:
  postgres: